services:
  # Основное приложение
  camera-api:
    image: node:18-alpine
    container_name: camera-api
    working_dir: /app
    ports:
      - "${PORT:-17777}:${PORT:-17777}"
    volumes:
      # Монтируем исходный код для hot reload
      - ./src:/app/src
      - ./package.json:/app/package.json:ro
      - ./package-lock.json:/app/package-lock.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      # Сохраняем node_modules в именованном volume для производительности
      - node_modules:/app/node_modules
      # Монтируем директории для логов, загрузок и временных файлов
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - ./temp:/app/temp
    env_file:
      - .env
    command: sh -c "npm ci && npm run start"
    restart: unless-stopped
    networks:
      - camera-network

  # Сервис для установки пакетов
  package-install:
    image: node:18-alpine
    container_name: camera-api-install
    working_dir: /app
    volumes:
      - ./package.json:/app/package.json:ro
      - ./package-lock.json:/app/package-lock.json:ro
      - node_modules:/app/node_modules
    command: ["npm", "install"]
    networks:
      - camera-network
    profiles:
      - install

volumes:
  node_modules:

networks:
  camera-network:
    driver: bridge